repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.0
    hooks:
      - id: terraform_checkov
        args:
          - --args=--skip-check CKV_AWS_23
          - --args=--skip-check CKV_AWS_18
          - --args=--skip-check CKV_AWS_109
          - --args=--skip-check CKV_AWS_111
          - --args=--skip-check CKV_AWS_144
          - --args=--skip-check CKV_AWS_145
          - --args=--skip-check CKV_AWS_149
          - --args=--skip-check CKV_AWS_274
          - --args=--skip-check CKV_AWS_356
          - --args=--skip-check CKV2_AWS_5
          - --args=--skip-check CKV2_AWS_57
          - --args=--skip-check CKV2_AWS_61
          - --args=--skip-check CKV2_AWS_62
          - --args=--skip-check CKV2_AWS_65
          - --args=--skip-check CKV_TF_1
          - --args=--skip-check CKV2_GHA_1
      - id: terraform_docs
      - id: terraform_docs_without_aggregate_type_defaults
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_trivy
      # - id: terraform_validate
      # - id: terrascan
      #   args:
      #     - --args=--non-recursive
      #     - --args=--skip-rules="AC_AWS_0500"
