name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: [self-hosted, core-shr]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pre-commit
        uses: grupoboticario/actions-tf-pre-commit@v1
